[package]
name = "holasui_quest"
version = "0.0.0"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
# mainnet-1.8.2
rev = "433090856ef070fc71c775b444c9a9070692664e"
## testnet-1.9.0
#rev = "f598b13b74f66d76d85190acfb127bab15afe3d2"

[addresses]
holasui_quest = "0x0"